# Generated by Django 4.0.4 on 2022-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='my_img')),
            ],
        ),
    ]
